cp1_data=read.csv("~/household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
cp1_data$Date=as.Date(cp1_data$Date, format="%d/%m/%Y")
data=subset(cp1_data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(data_full)
datetime=paste(as.Date(data$Date), data$Time)
data$Datetime=as.POSIXct(datetime)
plot(data$Global_active_power~data$Datetime, type="l",ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()
